{
  description = "dvim - Dane's Neovim configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      mkPackage =
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = true;
          };

          configDir = pkgs.stdenv.mkDerivation {
            name = "dvim-config";
            src = pkgs.lib.cleanSourceWith {
              src = ./.;
              filter = path: type: baseNameOf path != "result";
            };
            dontBuild = true;
            installPhase = ''
              cp -r . $out
            '';
          };

          # Neovim with magick Lua package for image rendering (image.nvim)
          neovimWithLua = pkgs.neovim.override {
            extraLuaPackages = luaPkgs: [ luaPkgs.magick ];
          };

          # Mirrors the tflint config generated by neovim.nix, stored in the Nix store
          tflintConfig = pkgs.writeText "tflint.hcl" ''
            plugin "terraform" {
              enabled = true
              preset  = "recommended"
            }

            plugin "aws" {
              enabled = true
              version = "${pkgs.tflint-plugins.tflint-ruleset-aws.version}"
              source  = "github.com/terraform-linters/tflint-ruleset-aws"
              deep_check = true
            }
          '';

          tools = with pkgs; [
            tree-sitter

            # LSP servers
            nixd
            lua-language-server
            basedpyright
            bash-language-server
            shellcheck # optional dep for bash-language-server linting
            terraform-ls
            yaml-language-server
            marksman
            vscode-langservers-extracted # JSON/HTML/CSS/ESLint LSPs
            gitlab-ci-ls
            harper

            # Formatters & linters
            stylua
            nixfmt
            ruff
            shfmt
            shellharden
            prettier
            yamlfmt
            markdownlint-cli
            checkmake
            vale
            commitlint # note: requires manual npm config (see README)

            # Tools
            imagemagick
            fzf
            fd
            ripgrep
            bat
            zoxide
            delta
            difftastic
            deno
            trivy
            terraform
            (tflint.withPlugins (p: [ p.tflint-ruleset-aws ]))
          ];
        in
        pkgs.writeShellScriptBin "dvim" ''
          export NVIM_APPNAME="dvim"
          export DVIM_ROOT="${configDir}"
          export TFLINT_CONFIG_FILE="${tflintConfig}"
          export PATH="${pkgs.lib.makeBinPath tools}:$PATH"
          exec ${neovimWithLua}/bin/nvim \
            --cmd "set rtp^=${configDir}" \
            -u ${configDir}/init.lua "$@"
        '';
    in
    {
      packages = forAllSystems (system: {
        default = mkPackage system;
      });

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${mkPackage system}/bin/dvim";
        };
      });

      # Home Manager module — use this instead of neovim.nix in your nix-dots
      homeManagerModules.default =
        {
          config,
          lib,
          pkgs,
          ...
        }:
        let
          cfg = config.programs.dvim;
          system = pkgs.stdenv.hostPlatform.system;
        in
        {
          options.programs.dvim = {
            enable = lib.mkEnableOption "dvim — Dane's Neovim configuration";

            neovide = {
              enable = lib.mkEnableOption "Neovide GUI frontend for dvim";
            };
          };

          config = lib.mkIf cfg.enable {
            home.packages = [
              self.packages.${system}.default
            ]
            ++ lib.optionals cfg.neovide.enable [ pkgs.neovide ];

            programs.neovide = lib.mkIf cfg.neovide.enable {
              enable = true;
              settings = {
                fork = false;
                frame = "full";
                idle = true;
                maximized = false;
                no-multigrid = false;
                srgb = false;
                tabs = true;
                theme = "auto";
                title-hidden = true;
                vsync = true;
                wsl = false;
              };
            };
          };
        };
    };
}
